name: egura_app
description: "eGura - Rwanda's Premier E-Commerce App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/logo.jpeg"
  ios:
    generate: true
  android:
    generate: true
  macos:
    generate: true
  windows:
    generate: true
  linux:
    generate: true
  web:
    generate: true
    image_path: "assets/images/logo.jpeg"
    background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
